# Generated by Django 3.1.7 on 2021-04-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionrating',
            options={'verbose_name': 'Оценка вопроса', 'verbose_name_plural': 'Оценки вопроса'},
        ),
        migrations.CreateModel(
            name='AnswerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
            options={
                'verbose_name': 'Оценка ответа',
                'verbose_name_plural': 'Оценки ответа',
            },
        ),
    ]
